openapi: 3.0.1
info:
  title: EmployeeDataAPI
  description: API Definition of EmployeeDataAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/employee
paths:
  /fetch_data:
    get:
      responses:
        default:
          description: Default response
